[package]
name = "table"
version = "0.1.0"
authors = ["kurt <kurtlawrence92@gmail.com>"]
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "*"

[[bench]]
name = "benches"
path = "benches.rs"
harness = false
